/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ascenseur1;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author DELL
 */
public class Simulation extends javax.swing.JFrame {
                 
        JRadioButton[] btnEtages = new JRadioButton[5];
    /**
     * Creates new form Simulation
     */
    public Simulation() {
        initComponents();
        scaleImage(this.lblRetChausse);
        scaleImagebtn();
        btnEtages[0] = btnEtage1;
        btnEtages[1] = btnEtage2;
        btnEtages[2] = btnEtage3;
        btnEtages[3] = btnEtage4;
        btnEtages[4] = btnEtage5;
    } 
    public void scaleImage(JLabel lblRetChausse){
        ImageIcon icon = new ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\Ascenseur\\src\\main\\java\\img\\ascenseur.png") ; 
    Image img = icon.getImage() ; 
    Image imgScale = img.getScaledInstance(lblRetChausse.getWidth(), lblRetChausse.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(imgScale);
    lblRetChausse.setIcon(scaledIcon);
    }
    public void scaleImagebtn(){
    ImageIcon icon = new ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\Ascenseur\\src\\main\\java\\img\\start.jpg") ; 
    Image img = icon.getImage() ; 
    Image imgScale = img.getScaledInstance(btnStart.getWidth(), btnStart.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(imgScale);
    btnStart.setIcon(scaledIcon);
    System.out.println(this.btnEtages[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblRetChausse = new javax.swing.JLabel();
        btnEtage1 = new javax.swing.JRadioButton();
        btnEtage2 = new javax.swing.JRadioButton();
        btnEtage3 = new javax.swing.JRadioButton();
        btnEtage4 = new javax.swing.JRadioButton();
        btnEtage5 = new javax.swing.JRadioButton();
        Descender = new javax.swing.JRadioButton();
        Monter = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        Arreter = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setOpaque(true);

        lblRetChausse.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRetChausse, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 45, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 45, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(lblRetChausse, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 235, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 236, Short.MAX_VALUE)))
        );

        buttonGroup1.add(btnEtage1);
        btnEtage1.setText("Etage1");

        buttonGroup1.add(btnEtage2);
        btnEtage2.setText("Etage2");
        btnEtage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtage2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnEtage3);
        btnEtage3.setText("Etage3");

        buttonGroup1.add(btnEtage4);
        btnEtage4.setText("Etage4");

        buttonGroup1.add(btnEtage5);
        btnEtage5.setText("Etage5");

        buttonGroup3.add(Descender);
        Descender.setText("Descender");

        buttonGroup3.add(Monter);
        Monter.setText("Monter");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ascenseur");

        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        buttonGroup3.add(Arreter);
        Arreter.setText("Arreter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEtage1)
                    .addComponent(btnEtage2)
                    .addComponent(btnEtage3)
                    .addComponent(btnEtage4)
                    .addComponent(btnEtage5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Descender)
                    .addComponent(Monter)
                    .addComponent(Arreter))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Arreter)
                                .addGap(18, 18, 18)
                                .addComponent(Descender)
                                .addGap(26, 26, 26)
                                .addComponent(Monter)
                                .addGap(243, 243, 243))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnEtage5)
                                .addGap(64, 64, 64)
                                .addComponent(btnEtage4)
                                .addGap(69, 69, 69)
                                .addComponent(btnEtage3)
                                .addGap(72, 72, 72)
                                .addComponent(btnEtage2)
                                .addGap(78, 78, 78)
                                .addComponent(btnEtage1)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEtage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtage2ActionPerformed
       
    }//GEN-LAST:event_btnEtage2ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

    Asenceur As = new Asenceur(5 , 1 ,lblRetChausse , Monter , Descender , btnEtages,Arreter );
    Personne p = new Personne(3 , As , 2) ;
    Personne p2 = new Personne(4 , As , 3) ;
    Personne p1 = new Personne(2 , As, 1) ;
    Thread Th = new Thread(p) ;
    Thread Th1 = new Thread(p1) ;
    Thread Th2 = new Thread(p2) ;
    Th.start();
    Th1.start();
    Th2.start();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Arreter;
    private javax.swing.JRadioButton Descender;
    private javax.swing.JRadioButton Monter;
    private javax.swing.JRadioButton btnEtage1;
    private javax.swing.JRadioButton btnEtage2;
    private javax.swing.JRadioButton btnEtage3;
    private javax.swing.JRadioButton btnEtage4;
    private javax.swing.JRadioButton btnEtage5;
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblRetChausse;
    // End of variables declaration//GEN-END:variables
}
