/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ascenseur2;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author DELL
 */
public class simulation2 extends javax.swing.JFrame {
    JRadioButton[] btnEtages = new JRadioButton[5];
    JRadioButton[] btnEtages2 = new JRadioButton[5];

    /**
     * Creates new form simulation2
     */
    public simulation2() {
        initComponents();
        btnEtages[0] = Etage1;
        btnEtages[1] = Etage2;
        btnEtages[2] = Etage3;
        btnEtages[3] = Etage4;
        btnEtages[4] = Etage5;
        btnEtages2[0] = Etage21;
        btnEtages2[1] = Etage22;
        btnEtages2[2] = Etage23;
        btnEtages2[3] = Etage24;
        btnEtages2[4] = Etage25;
        scaleImage(RetChausse);
        scaleImage(RetChausse1);
        scaleImagebtn( btnStart); 
        scaleImagebtn( btnStart1);

    }
public void scaleImage(JLabel lblRetChausse){
    ImageIcon icon = new ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\Ascenseur\\src\\main\\java\\img\\ascenseur.png") ; 
    Image img = icon.getImage() ; 
    Image imgScale = img.getScaledInstance(lblRetChausse.getWidth(), lblRetChausse.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(imgScale);
    lblRetChausse.setIcon(scaledIcon);
    }
public void scaleImagebtn(JButton btnStart){
    ImageIcon icon = new ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\Ascenseur\\src\\main\\java\\img\\start.jpg") ; 
    Image img = icon.getImage() ; 
    Image imgScale = img.getScaledInstance(btnStart.getWidth(), btnStart.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(imgScale);
    btnStart.setIcon(scaledIcon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        RetChausse1 = new javax.swing.JLabel();
        Arreter = new javax.swing.JRadioButton();
        Descender = new javax.swing.JRadioButton();
        Monter = new javax.swing.JRadioButton();
        Etage2 = new javax.swing.JRadioButton();
        Etage1 = new javax.swing.JRadioButton();
        Etage3 = new javax.swing.JRadioButton();
        Etage5 = new javax.swing.JRadioButton();
        Etage4 = new javax.swing.JRadioButton();
        btnStart = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        RetChausse = new javax.swing.JLabel();
        Arreter1 = new javax.swing.JRadioButton();
        Descender1 = new javax.swing.JRadioButton();
        Monter1 = new javax.swing.JRadioButton();
        Etage22 = new javax.swing.JRadioButton();
        Etage21 = new javax.swing.JRadioButton();
        Etage23 = new javax.swing.JRadioButton();
        Etage25 = new javax.swing.JRadioButton();
        Etage24 = new javax.swing.JRadioButton();
        btnStart1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        RetChausse1.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RetChausse1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(RetChausse1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup3.add(Arreter);
        Arreter.setText("Arreter");

        buttonGroup3.add(Descender);
        Descender.setText("Descender");

        buttonGroup3.add(Monter);
        Monter.setText("Monter");

        buttonGroup4.add(Etage2);
        Etage2.setText("Etage2");

        buttonGroup4.add(Etage1);
        Etage1.setText("Etage1");

        buttonGroup4.add(Etage3);
        Etage3.setText("Etage3");

        buttonGroup4.add(Etage5);
        Etage5.setText("Etage5");
        Etage5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Etage5ActionPerformed(evt);
            }
        });

        buttonGroup4.add(Etage4);
        Etage4.setText("Etage4");
        Etage4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Etage4ActionPerformed(evt);
            }
        });

        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Etage1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Etage2)
                                    .addComponent(Etage5))
                                .addGap(84, 103, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Etage3)
                                    .addComponent(Etage4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Monter)
                                    .addComponent(Descender)
                                    .addComponent(Arreter))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Etage5)
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Etage4)
                        .addGap(56, 56, 56)
                        .addComponent(Etage3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Etage2)
                        .addGap(68, 68, 68)
                        .addComponent(Etage1)
                        .addGap(132, 132, 132))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Arreter)
                        .addGap(18, 18, 18)
                        .addComponent(Descender)
                        .addGap(18, 18, 18)
                        .addComponent(Monter)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        RetChausse.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RetChausse, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(RetChausse, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(Arreter1);
        Arreter1.setText("Arreter");

        buttonGroup1.add(Descender1);
        Descender1.setText("Descender");

        buttonGroup1.add(Monter1);
        Monter1.setText("Monter");

        buttonGroup2.add(Etage22);
        Etage22.setText("Etage2");

        buttonGroup2.add(Etage21);
        Etage21.setText("Etage1");

        buttonGroup2.add(Etage23);
        Etage23.setText("Etage3");

        buttonGroup2.add(Etage25);
        Etage25.setText("Etage5");
        Etage25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Etage25ActionPerformed(evt);
            }
        });

        buttonGroup2.add(Etage24);
        Etage24.setText("Etage4");
        Etage24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Etage24ActionPerformed(evt);
            }
        });

        btnStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Etage21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Etage23)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Monter1)
                                    .addComponent(Descender1)
                                    .addComponent(Arreter1)))
                            .addComponent(Etage22)
                            .addComponent(Etage24)
                            .addComponent(Etage25))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(Arreter1)
                .addGap(18, 18, 18)
                .addComponent(Descender1)
                .addGap(18, 18, 18)
                .addComponent(Monter1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Etage25)
                        .addGap(61, 61, 61)
                        .addComponent(Etage24)
                        .addGap(56, 56, 56)
                        .addComponent(Etage23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(Etage22)
                        .addGap(68, 68, 68)
                        .addComponent(Etage21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Etage4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Etage4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Etage4ActionPerformed

    private void Etage5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Etage5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Etage5ActionPerformed

    private void Etage25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Etage25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Etage25ActionPerformed

    private void Etage24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Etage24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Etage24ActionPerformed

    private void btnStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart1ActionPerformed
    Ascenseur2.Asenceur As = new Ascenseur2.Asenceur(5 , 1 ,RetChausse , Monter1 , Descender1 , btnEtages2,Arreter1 );
    Ascenseur2.Personne p = new Ascenseur2.Personne(3 , As , 2) ;
    Ascenseur2.Personne p2 = new Ascenseur2.Personne(4 , As , 3) ;
    Ascenseur2.Personne p1 = new Ascenseur2.Personne(2 , As, 1) ;
    Thread Th = new Thread(p) ;
    Thread Th1 = new Thread(p1) ;
    Thread Th2 = new Thread(p2) ;
    Th.start();
    Th1.start();
    Th2.start();
    }//GEN-LAST:event_btnStart1ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
    Ascenseur2.Asenceur As = new Ascenseur2.Asenceur(5 , 1 ,RetChausse1 , Monter , Descender , btnEtages,Arreter );
    Ascenseur2.Personne p = new Ascenseur2.Personne(5 , As , 2) ;
    Ascenseur2.Personne p2 = new Ascenseur2.Personne(2 , As , 3) ;
    Ascenseur2.Personne p1 = new Ascenseur2.Personne(4 , As, 1) ;
    Thread Th = new Thread(p) ;
    Thread Th1 = new Thread(p1) ;
    Thread Th2 = new Thread(p2) ;
    Th.start();
    Th1.start();
    Th2.start();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simulation2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simulation2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simulation2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simulation2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simulation2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Arreter;
    private javax.swing.JRadioButton Arreter1;
    private javax.swing.JRadioButton Descender;
    private javax.swing.JRadioButton Descender1;
    private javax.swing.JRadioButton Etage1;
    private javax.swing.JRadioButton Etage2;
    private javax.swing.JRadioButton Etage21;
    private javax.swing.JRadioButton Etage22;
    private javax.swing.JRadioButton Etage23;
    private javax.swing.JRadioButton Etage24;
    private javax.swing.JRadioButton Etage25;
    private javax.swing.JRadioButton Etage3;
    private javax.swing.JRadioButton Etage4;
    private javax.swing.JRadioButton Etage5;
    private javax.swing.JRadioButton Monter;
    private javax.swing.JRadioButton Monter1;
    private javax.swing.JLabel RetChausse;
    private javax.swing.JLabel RetChausse1;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStart1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
